[package]
name = "maloca"
version = "0.1.0"
authors = ["Carlos Galdino <carloshsgaldino@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "0.7.0"
spin   = "0.5"
